### ISSUE TITLE
Error after selecting organization

### ISSUE THREAD

**Issue by Rec916** [CiscoSecurity/amp-04-export-exclusions#4]
Which organization would you like to list exclusions from?
[1] - My org
Input a number listed above: 1
Which exclusion set would you like to list exclusions from?
Traceback (most recent call last):
  File "amp-04-export-exclusions.py", line 249, in <module>
    exclusion_set_info = select_exclusion_set(exclusion_sets, se_access_token, org_id)
  File "amp-04-export-exclusions.py", line 128, in select_exclusion_set
    print(f"[{idx + 1}] - {exclusion_set['name']}")
KeyError: 'name'

**Comment by mafranks** [comment]
Sorry it took so long to fix this, I don't recall seeing a notification. The format went from each exclusion having a "name" field to being nested under "properties". Should be good now.
